language: node_js
sudo: false
node_js:
  - 6
email:
  on_failure: change
  on_success: never
install:
  - yarn
script:
  - yarn jest --coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)